name: where_watch_app
description: Open source application to find on which platform a certain films or series have.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.3 <3.0.0"

scripts:
  test: flutter test --coverage test/
  gen_coverage: perl %GENHTML% -o coverage\html coverage\lcov.info
  analyze: dartanalyzer .
  format: dartfmt -w .
  refresh: flutter pub get

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/fonts/
    - lib/assets/animations/

fonts:
  - family: BW Seido
    fonts:
      - asset: lib/assets/fonts/bw_seido_round_regular.otf
      - asset: lib/assets/fonts/bw_seido_round_bold.otf
        weight: 800
      - asset: lib/assets/fonts/bw_seido_round_light.otf
        weight: 300
