name: where_watch_app
description: Open source application to find on which platform a certain films or series have.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.3 <3.0.0"

scripts:
  test: flutter test --coverage test/
  gen_coverage: perl %GENHTML% -o coverage\html coverage\lcov.info
  analyze: dartanalyzer .
  format: dartfmt -w .
  refresh: flutter pub get

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.1.4
  rx_notifier: ^1.1.0
  font_awesome_flutter: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/fonts/
    - lib/assets/animations/

fonts:
  - family: BWSeido
    fonts:
      - asset: lib/assets/fonts/bw-seido-regular.ttf
      - asset: lib/assets/fonts/bw-seido-bold.ttf
        weight: 800
      - asset: lib/assets/fonts/bw-seido-light.ttf
        weight: 300

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/images/icon.png"

flutter_native_splash:
  flutter_native_splash:
  image: "lib/assets/images/logo.png"
  color: "2A272E"
  android_disable_fullscreen: true
